### ISSUE TITLE
Installation fails on nodejs 7.8.0

### ISSUE THREAD

**Issue by killmenot** [bretcope/node-gc-profiler#13]
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.5 LTS"
NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.5 LTS"
VERSION_ID="14.04"
```

```
161902 verbose stack Error: gc-profiler@1.4.0 install: `node-gyp rebuild`
161902 verbose stack Exit status 1
161902 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
161902 verbose stack     at emitTwo (events.js:106:13)
161902 verbose stack     at EventEmitter.emit (events.js:194:7)
161902 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
161902 verbose stack     at emitTwo (events.js:106:13)
161902 verbose stack     at ChildProcess.emit (events.js:194:7)
161902 verbose stack     at maybeClose (internal/child_process.js:899:16)
161902 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
161903 verbose pkgid gc-profiler@1.4.0
161904 verbose cwd /var/www/myApp
161905 error Linux 3.13.0-92-generic
161906 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
161907 error node v7.8.0
161908 error npm  v4.2.0
161909 error code ELIFECYCLE
161910 error errno 1
161911 error gc-profiler@1.4.0 install: `node-gyp rebuild`
161911 error Exit status 1
161912 error Failed at the gc-profiler@1.4.0 install script 'node-gyp rebuild'.
161912 error Make sure you have the latest version of node.js and npm installed.
161912 error If you do, this is most likely a problem with the gc-profiler package,
161912 error not with npm itself.
161912 error Tell the author that this fails on your system:
161912 error     node-gyp rebuild
161912 error You can get information on how to open an issue for this project with:
161912 error     npm bugs gc-profiler
161912 error Or if that isn't available, you can get their info via:
161912 error     npm owner ls gc-profiler
161912 error There is likely additional logging output above.
```

**Comment by orgads** [comment]
Is this still actual? Closing for now.
